config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "products#index"
  resources :products do
    resources :listings
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :product
  def self.search_by(search_term)
    where("LOWER(model) ||  LOWER(year) LIKE :search_term", search_term: "%#{search_term.downcase}%")
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :listings, dependent: :destroy

  def self.alphabetical
    order("name")
  end

  def self.search_by(search_term)
    where("LOWER(name) LIKE :search_term", search_term: "%#{search_term.downcase}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!

  def index
    # @listings = Listing.all
    @product = Product.find(params[:product_id])
    @listings = @product.listings
    if params[:search]
      @search_term = params[:search]
      @listings = @listings.search_by(@search_term)
    end
  end

  def new
    @product = Product.find(params[:product_id])
    @listing = @product.listings.new
  end

  def create
    @product = Product.find(params[:product_id])
    @listing = @product.listings.new(listing_params)
    if @listing.save
      redirect_to product_listings_path(@product), notice: "You added a listing!"
    else
      render :new
    end
  end

private

  def listing_params
    params.require(:listing).permit(:model, :year, :color)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!

  def index
    # @products = Product.alphabetical
    @products = Product.alphabetical
    if params[:search]
      @search_term = params[:search]
      @products = @products.search_by(@search_term)
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to @product, notice: "Product successfully updated!"
    else
      render :edit
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_url(@product), notice: "Thanks for adding!"
    else
      render :new
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_url, alert: "Product successfully deleted!"
  end

end

private

  def product_params
    params.require(:product).permit(:name)
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_flashes.html.erb
<!-- <% if flash[:notice] %>
<p class="notice"><%= flash[:notice] %></p>
<% end %> -->
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, :class => "flash #{key}") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SomethingCarRelated</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/flashes" %>


    <%= yield %>
  </body>
</html>

app/views/listings/index.html.erb
<h1>Listings for <%= link_to(@product.name, @product) %></h1>

<% @listings.each do |l| %>
<li>
  <%= l.year %>
  <%= l.product.name %>
  <%= l.model %>
  <%= l.color %>
</li>


<% end %>

<%= link_to "Create new listing", new_product_listing_path(@product) %>
<br>
<%= link_to "All Products", root_path %>

<%= form_for "",url: product_listings_path, role: "search", method: :get do %>
  <%= text_field_tag :search, @search_term, placeholder: "Search by Model or Year" %>
<% end %>

app/views/listings/new.html.erb
<h1>Listings for <%= link_to @product.name, @product %></h1>

<%= form_for([@product, @listing]) do |f| %>
  <%= f.label :model %>
  <%= f.text_field :model, autofocus:true %>
  <br>
  <br>
  <%= f.label :year %>
  <%= f.select :year, (Time.zone.now.year - 200)..(Time.zone.now.year + 2) %>
  <br>
  <br>
  <%= f.label :color %>
  <%= f.text_field :color, autofocus:true %>
  <br>
  <br>
  <%= f.submit "Post Listing" %> |
  <%= link_to "Cancel", @product %>
<% end %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <p>
    <%= f.label :name %> <br>
    <%= f.text_field :name, autofocus: true %>
  </p>
  <%= f.submit %> |
  <%= link_to "Cancel", products_path %>
  <% end %>

app/views/products/edit.html.erb
<h1>Editing <%= @product.name %></h1>

<%= render 'form' %>

app/views/products/index.html.erb
<h1><%= pluralize(@products.size, 'Product') %></h1>

<%= link_to "Add New Product", new_product_path %>

<ul>
  <% @products.each do |product| %>
  <li>
    <%= link_to(product.name, product) %>
  </li>
  <% end %>
</ul>

<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path) %>
  </li>
<% end %>

<%= form_for "",url: products_path, role: "search", method: :get do %>
  <%= text_field_tag :search, @search_term, placeholder: "Search by Make" %>
<% end %>

app/views/products/new.html.erb
<h1>Add New Event</h1>

<%= render 'form' %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<h1><%= link_to "Click here to view all listings", product_listings_path(@product) %></h1>

<br> <br>
<%= link_to "Create new listing", new_product_listing_path(@product) %>
<br>

<%= link_to "All Products", root_path %> |
<%= link_to "Edit", edit_product_path(@product) %> |
<%= link_to "Delete", product_path(@product), method: :delete, data: {confirm: 'Are you sure you want to delete?'} %>